<?php

namespace AppBundle\Repository;

/**
 * coffeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coffeRepository extends \Doctrine\ORM\EntityRepository
{
}
